export const elements = {
	1: {
		type: 'прямоугольник',
		width: 15,
		height: 5,
		name: 'Секция',
		position: { x: 10, y: 11 },
	},
	2: {
		type: 'прямоугольник',
		width: 6,
		height: 16,
		name: 'Ксиеця',
		position: { x: 48, y: 50 },
	},
	3: {
		type: 'прямоугольник',
		width: 7,
		height: 17,
		name: 'Основа',
		position: { x: 51, y: 52 },
	},
	4: {
		type: 'прямоугольник',
		width: 25,
		height: 10,
		name: 'Модуль',
		position: { x: 21, y: 20 },
	},
	5: {
		type: 'прямоугольник',
		width: 11,
		height: 26,
		name: 'Льмоду',
		position: { x: 41, y: 40 },
	},
	6: {
		type: 'прямоугольник',
		width: 12,
		height: 27,
		name: 'дуМоль',
		position: { x: 60, y: 61 },
	},
	7: {
		type: 'прямоугольник',
		width: 35,
		height: 8,
		name: 'Рама',
		position: { x: 33, y: 34 },
	},
	8: {
		type: 'прямоугольник',
		width: 9,
		height: 36,
		name: 'Арма',
		position: { x: 35, y: 36 },
	},
	9: {
		type: 'прямоугольник',
		width: 10,
		height: 37,
		name: 'Марр',
		position: { x: 54, y: 53 },
	},
}